"""v8

Revision ID: 20cb3f17cf3f
Revises: 
Create Date: 2024-05-30 00:31:24.590808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20cb3f17cf3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_unique_constraint('_customer_company_uc', ['customer_id', 'company_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint('_customer_company_uc', type_='unique')

    # ### end Alembic commands ###
