"""lead table modified

Revision ID: 72462d2a4f7c
Revises: 20cb3f17cf3f
Create Date: 2024-05-30 00:44:30.962453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72462d2a4f7c'
down_revision = '20cb3f17cf3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inquiry_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('inquiry_type')

    # ### end Alembic commands ###
